### ISSUE TITLE
运行环境和数据

### ISSUE THREAD

**Issue by JINGJINGANDQIQI** [ufal/MLASK#2]
你好，你们的环境配置版本能给一下吗？还有你们的数据，给个demo也行

**Comment by mateuk** [comment]
I've added the `requirements.txt` used in our experiments. Regarding the data - if this repo is not updated by the end of this month, please contact me via email for a data sample.

**Comment by JINGJINGANDQIQI** [comment]
![1684552937231](https://github.com/ufal/MLASK/assets/48210746/ffd176d4-84e9-4fbc-a028-8b67b8f6a2ce)
这类文件怎么获取谢谢
